version: "3"
services:
  dev-db:
    image: postgres:15-alpine
    container_name: dev-postgres
    restart: always 
    ports:
      - ${DEV_POSTGRES_PORT}:5432
    # volumes:
    #   - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB_NAME}


  test-db:
    image: postgres:15-alpine
    container_name: test-postgres
    restart: unless-stopped
    ports:
      - ${TEST_POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB_NAME}